/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas11;

/**
 *
 * @author HELLO
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TabelMahasiswa extends javax.swing.JFrame {
    DefaultTableModel modelMahasiswa;
    InputDataMahasiswa dataMahasiswa;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TabelMahasiswa.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public TabelMahasiswa() {
        initComponents();
        dataMahasiswa = new InputDataMahasiswa();
        viewDataTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        nim = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        makul = new javax.swing.JLabel();
        nilai1 = new javax.swing.JLabel();
        nilai2 = new javax.swing.JLabel();
        nilai3 = new javax.swing.JLabel();
        nilai4 = new javax.swing.JLabel();
        nilai5 = new javax.swing.JLabel();
        nilaiAkhir = new javax.swing.JLabel();
        nimTF = new javax.swing.JTextField();
        namaTF = new javax.swing.JTextField();
        alamatTF = new javax.swing.JTextField();
        makulTF = new javax.swing.JTextField();
        nilai1TF = new javax.swing.JTextField();
        nilai2TF = new javax.swing.JTextField();
        nilai3TF = new javax.swing.JTextField();
        nilai4TF = new javax.swing.JTextField();
        nilai5TF = new javax.swing.JTextField();
        nilaiAkhirTF = new javax.swing.JTextField();
        simpanBT = new javax.swing.JButton();
        hapusBT = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        mahasiswaTB = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        nim.setForeground(new java.awt.Color(0, 0, 0));
        nim.setText("NIM");

        nama.setForeground(new java.awt.Color(0, 0, 0));
        nama.setText("Nama");

        alamat.setForeground(new java.awt.Color(0, 0, 0));
        alamat.setText("Alamat");

        makul.setForeground(new java.awt.Color(0, 0, 0));
        makul.setText("Mata Kuliah");

        nilai1.setForeground(new java.awt.Color(0, 0, 0));
        nilai1.setText("Nilai 1 [10%]");

        nilai2.setForeground(new java.awt.Color(0, 0, 0));
        nilai2.setText("Nilai 2 [15%]");

        nilai3.setForeground(new java.awt.Color(0, 0, 0));
        nilai3.setText("Nilai 3 - UTS[25%]");

        nilai4.setForeground(new java.awt.Color(0, 0, 0));
        nilai4.setText("Nilai 4 [15%]");

        nilai5.setForeground(new java.awt.Color(0, 0, 0));
        nilai5.setText("Nilai 5 [35%]");

        nilaiAkhir.setForeground(new java.awt.Color(0, 0, 0));
        nilaiAkhir.setText("Nilai Akhir");

        nimTF.setBackground(new java.awt.Color(255, 255, 255));
        nimTF.setForeground(new java.awt.Color(0, 0, 0));

        namaTF.setBackground(new java.awt.Color(255, 255, 255));
        namaTF.setForeground(new java.awt.Color(0, 0, 0));

        alamatTF.setBackground(new java.awt.Color(255, 255, 255));
        alamatTF.setForeground(new java.awt.Color(0, 0, 0));

        makulTF.setBackground(new java.awt.Color(255, 255, 255));
        makulTF.setForeground(new java.awt.Color(0, 0, 0));

        nilai1TF.setBackground(new java.awt.Color(255, 255, 255));
        nilai1TF.setForeground(new java.awt.Color(0, 0, 0));

        nilai2TF.setBackground(new java.awt.Color(255, 255, 255));
        nilai2TF.setForeground(new java.awt.Color(0, 0, 0));

        nilai3TF.setBackground(new java.awt.Color(255, 255, 255));
        nilai3TF.setForeground(new java.awt.Color(0, 0, 0));

        nilai4TF.setBackground(new java.awt.Color(255, 255, 255));
        nilai4TF.setForeground(new java.awt.Color(0, 0, 0));

        nilai5TF.setBackground(new java.awt.Color(255, 255, 255));
        nilai5TF.setForeground(new java.awt.Color(0, 0, 0));

        nilaiAkhirTF.setBackground(new java.awt.Color(255, 255, 255));
        nilaiAkhirTF.setForeground(new java.awt.Color(0, 0, 0));
        nilaiAkhirTF.addActionListener(this::nilaiAkhirTFActionPerformed);

        simpanBT.setText("Simpan");
        simpanBT.addActionListener(this::simpanBTActionPerformed);

        hapusBT.setText("Hapus");
        hapusBT.addActionListener(this::hapusBTActionPerformed);

        mahasiswaTB.setBackground(new java.awt.Color(255, 255, 255));
        mahasiswaTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Alamat", "Mata Kuliah", "Nilai Akhir"
            }
        ));
        jScrollPane2.setViewportView(mahasiswaTB);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamat)
                    .addComponent(makul)
                    .addComponent(nim)
                    .addComponent(nama))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(simpanBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hapusBT))
                    .addComponent(nimTF, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamatTF, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makulTF, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nilai5)
                    .addComponent(nilaiAkhir)
                    .addComponent(nilai2)
                    .addComponent(nilai1)
                    .addComponent(nilai3)
                    .addComponent(nilai4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nilai1TF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(nilai2TF, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nilai3TF, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nilai4TF, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nilai5TF, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nilaiAkhirTF, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nim)
                    .addComponent(nilai1)
                    .addComponent(nimTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nilai1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama)
                    .addComponent(nilai2)
                    .addComponent(namaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nilai2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamat)
                    .addComponent(nilai3)
                    .addComponent(alamatTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nilai3TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(makul)
                    .addComponent(nilai4)
                    .addComponent(makulTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nilai4TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nilai5)
                    .addComponent(nilai5TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nilaiAkhir)
                    .addComponent(nilaiAkhirTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpanBT)
                    .addComponent(hapusBT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public final void viewDataTabel(){
        String[] namaKolom = {"NIM","Nama","Alamat","Mata Kuliah","Nilai Akhir"};
        Object[][] objekMahasiswa = new Object[dataMahasiswa.getALL().size()][5];
        int i = 0;
        for(Mahasiswa mhs: dataMahasiswa.getALL()){
            String arrayMahasiswa[] = {
            mhs.getnim(),
            mhs.getnama(),
            mhs.getalamat(),
            mhs.getmakul(),
            String.valueOf(mhs.getnilaiAkhir())
            };
            objekMahasiswa[i] = arrayMahasiswa;
            i++;
        }
        modelMahasiswa = new DefaultTableModel(objekMahasiswa, namaKolom);
        mahasiswaTB.setModel(modelMahasiswa);
    }
    
    public void clearTextField(){
        nimTF.setText("");
        namaTF.setText("");
        alamatTF.setText("");
        makulTF.setText("");
        nilai1TF.setText("");
        nilai2TF.setText("");
        nilai3TF.setText("");
        nilai4TF.setText("");
        nilai5TF.setText("");
        nilaiAkhirTF.setText("");
        nimTF.requestFocus();
    }
    
    private void simpanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBTActionPerformed
        double n1 = Double.parseDouble(nilai1TF.getText()) * 0.10;
        double n2 = Double.parseDouble(nilai2TF.getText()) * 0.15;
        double n3 = Double.parseDouble(nilai3TF.getText()) * 0.25;
        double n4 = Double.parseDouble(nilai4TF.getText()) * 0.15;
        double n5 = Double.parseDouble(nilai5TF.getText()) * 0.35;
        double nilaiAkhir = n1 + n2 + n3 + n4 + n5;
        nilaiAkhirTF.setText(String.valueOf(nilaiAkhir));
        double nilaiAkhir1 = Double.parseDouble(nilaiAkhirTF.getText());
        if(nilaiAkhirTF.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nilai akhir harus diisi");
        }
        dataMahasiswa.insertData(
            nimTF.getText(),
            namaTF.getText(),
            alamatTF.getText(),
            makulTF.getText(),
            nilaiAkhir
        );
        viewDataTabel();
        clearTextField();
    }//GEN-LAST:event_simpanBTActionPerformed

    private void hapusBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBTActionPerformed
        dataMahasiswa.deleteData(mahasiswaTB.getSelectedRow());
        viewDataTabel();
    }//GEN-LAST:event_hapusBTActionPerformed

    private void nilaiAkhirTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiAkhirTFActionPerformed
        
    }//GEN-LAST:event_nilaiAkhirTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TabelMahasiswa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat;
    private javax.swing.JTextField alamatTF;
    private javax.swing.JButton hapusBT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable mahasiswaTB;
    private javax.swing.JLabel makul;
    private javax.swing.JTextField makulTF;
    private javax.swing.JLabel nama;
    private javax.swing.JTextField namaTF;
    private javax.swing.JLabel nilai1;
    private javax.swing.JTextField nilai1TF;
    private javax.swing.JLabel nilai2;
    private javax.swing.JTextField nilai2TF;
    private javax.swing.JLabel nilai3;
    private javax.swing.JTextField nilai3TF;
    private javax.swing.JLabel nilai4;
    private javax.swing.JTextField nilai4TF;
    private javax.swing.JLabel nilai5;
    private javax.swing.JTextField nilai5TF;
    private javax.swing.JLabel nilaiAkhir;
    private javax.swing.JTextField nilaiAkhirTF;
    private javax.swing.JLabel nim;
    private javax.swing.JTextField nimTF;
    private javax.swing.JButton simpanBT;
    // End of variables declaration//GEN-END:variables
}
